name: calc-ir

on:
  push:
    paths: rust/calc-ir
  pull_request:
    paths: rust/calc-ir

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd rust/calc-ir && cargo build --verbose
    - name: Run tests
      run: cd rust/calc-ir && cargo test --verbose
