name: fuzzil-rs

on:
  push:
    paths: rust/fuzzil-rs
  pull_request:
    paths: rust/fuzzil-rs

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd rust/fuzzil-rs && cargo build --verbose
    - name: Run tests
      run: cd rust/fuzzil-rs && cargo test --verbose
